[project]
dependencies = [
    "bittensor @ git+https://github.com/backend-developers-ltd/bittensor@test-remove-cuda",
]
requires-python = "==3.11.*"

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-xdist",
    "requests",
    "-e compute-horde @ file:///${PROJECT_ROOT}/compute_horde/",
    "-e file:///${PROJECT_ROOT}/miner",
    "-e file:///${PROJECT_ROOT}/executor",
    "-e file:///${PROJECT_ROOT}/validator",
]
